### ISSUE TITLE
8.2 Research: Which AI-agent should we use

### ISSUE THREAD

**Issue by SofieLouise** [simonmdsn/CrazyCurve#43]

**Comment by joachimbulow** [comment]
Sense/Think/Act cycle:

**Sense:** The agent detects - or is told about - things in their environment that may influence their behaviour (e.g. threats nearby, items to collect, points of interest to investigate)
**Think:** The agent makes a decision about what to do in response (e.g. considers whether it is safe enough to collect items, or whether it should focus on fighting or hiding first)
**Act:** The agent performs actions to put the previous decision into motion (e.g. starts moving along a path towards the enemy, or towards the item, etc)
...the situation has now changed, due to the actions of the characters, so the cycle must repeat with the new data.

Decision trees

**Comment by joachimbulow** [comment]
A* is good for fining shortest path, but is this viable in this game?
Or should we invest time in something like Q-learning?
